### ISSUE TITLE
Allow to launch the vr mode without being in fullscreen

### ISSUE THREAD

**Issue by yannliepallotools** [googlevr/webvr-polyfill#114]
When the webvr-polyfill is used in the android web-view inside an application in can't launch the vr mode because it won't go in fullscreen

**Comment by borismus** [comment]
Are you sure its impossible?
https://github.com/electron/electron/issues/1503 might have some relevant
info. Otherwise you can do what we do in iOS.

**Comment by cvan** [comment]
AFAIK, even with a Chromium/Firefox flag, there is no way to disable Fullscreen API's required ["engagement gesture"](https://www.w3.org/TR/pointerlock/#dfn-engagement-gesture) for calling `requestFullscreen`. Relevant: https://html.spec.whatwg.org/#allowed-to-show-a-popup

There used to be `--disable-gesture-requirement-for-media-fullscreen` (which _appears_ to have been for the Fullscreen API), but the flag was [removed](https://bugs.chromium.org/p/chromium/issues/detail?id=350385). And for the Presentation API the [`--disable-gesture-requirement-for-presentation`](https://groups.google.com/a/chromium.org/forum/#!msg/blink-reviews/OSmrEWoMkIs/UJVMRZIHGgAJ) flag was introduced, but's it's not for the Fullscreen API.

Also relevant, slightly related discussion: #108

**Comment by hugohil** [comment]
Any update on this ?
I encountered the same issue using aframe in a Cordova app and a couple hours of research lead me here.

Using any other mobile hybrid framework would cause the same, as well as Electron, NW.js or any Chromium embedded hybrid solution that already handles the fullscreen at a higher level. For anyone building a kiosk hybrid VR app, this is a real issue.

**Comment by yannliepallotools** [comment]
We've changed the code to match our needs : 

We created the function 
```
Util.isWebViewAndroid = (function() {
  var isWebViewAndroid = navigator.userAgent.indexOf('Version') !== -1 &&
      navigator.userAgent.indexOf('Android') !== -1 &&
      navigator.userAgent.indexOf('Chrome') !== -1;
  return function() {
    return isWebViewAndroid;
  };
})();
```

And in the requestFullscreen function we return false when it detects that it's on a webview

`Util.requestFullscreen = function(element) {
    if (Util.isWebViewAndroid()) {
        return false;
    }
`
And in the base.js when the present function is called we changed the code from

`      } else if (Util.isIOS()){
`

to
`      } else if (Util.isIOS() || Util.isWebViewAndroid()){
`

I hope it will help you.

**Comment by hugohil** [comment]
@yannliepallotools Thanks!! That helped me a lot :)

Had to remove the `indexOf('Version')` though (was not present in userAgent string) check though. Not sure what it does, any particular reason it's here ?

**Comment by yannliepallotools** [comment]
It was present in the webview for Android in Java, it's used to detect if it's the webview or the chrome browser (according to the Android documentation)

**Comment by andymartinwork** [comment]
The PR for the solution of this bug was explicitly denied.
Can we please get it opened and submitted again?

https://github.com/googlevr/webvr-polyfill/pull/175

**Comment by jsantell** [comment]
Closed via e55d7172b9665ef5316434095c783706a3b59758 from aframe's fork

**Comment by jeanmatthieud** [comment]
What about using Crosswalk ? https://crosswalk-project.org/

**Comment by jsantell** [comment]
From Crosswalk's landing page: "Important: This project is not maintained anymore. The last Crosswalk release was Crosswalk 23. Read more in this announcement"
