### ISSUE TITLE
es6-promise conflicts

### ISSUE THREAD

**Issue by zazabe** [googlevr/webvr-polyfill#118]
We are using https://github.com/petkaantonov/bluebird for our application and `es6-promise` is conflicting with it.

I'm wondering if it would not be better to remove this `es6-promise` dependency and add some info in the readme about Promises, something like "Promises are required and some Promise polyfills are available for incompatible browsers", wdyt?

_Currently, the only solution we have is to fork this repo and to remove this line: `require('es6-promise').polyfill()`_

**Comment by brianchirls** [comment]
It sounds like this might be an issue with either bluebird or es6-promise. It's better to understand exactly what the problem is and then file a bug issue or pull request with the offending library, rather than compromise this one.

Can you describe in more detail what the problem is?

**Comment by zazabe** [comment]
bluebird has a [`Promise.config`](http://bluebirdjs.com/docs/api/promise.config.html) method, we call it after that all js assets have been loaded (including `webvr-polyfill`). 
The problem is that `require('es6-promise').polyfill()` will override the bluebird's `Promise`, so this `Promise.config` will not be available anymore...

The [auto-polyfill](https://github.com/stefanpenner/es6-promise#auto-polyfill) method of `es6-promise` is a bit intrusive, please consider this alternative: https://github.com/zazabe/webvr-polyfill/tree/es6-promise.

**Comment by borismus** [comment]
No longer requiring the promise polyfill.
