### ISSUE TITLE
Use transform to remove hardcode data URIs for wakelock video, rotate-instructions icons

### ISSUE THREAD

**Issue by jeromeetienne** [googlevr/webvr-polyfill#120]
- [src/rotate-instructions.js](https://github.com/borismus/webvr-polyfill/blob/master/src/rotate-instructions.js) contains a line of 53000 characters [this one](https://github.com/borismus/webvr-polyfill/blob/master/src/rotate-instructions.js#L141)
- it seems to be good at slowing down editors like sublime text, or even crashing atom 

i would not call that a bug. just wanted to share the experience :)

**Comment by cvan** [comment]
I was working on a local branch that used a browserify-transform to inject the data URIs used so they wouldn't have to be embedded like so: https://github.com/borismus/webvr-polyfill/blob/a9ea232/src/rotate-instructions.js#L141

IMO, I would change the issue to be `Use transform to remove hardcode data URIs for wakelock video, rotate-instructions icons` or something.

**Comment by jeromeetienne** [comment]
glad you are working on it.

change done btw :)

**Comment by cvan** [comment]
would reopen

**Comment by borismus** [comment]
Not familiar with browserify-transform, but open to using it instead of having the wakelock video hardcoded.

**Comment by brianchirls** [comment]
As it is, this file is the single biggest script component in my entire library. Just the base64-encoded SVG is around 52k. It would be smaller (~40k) just included as text, and smaller still if you run it through [svgo](https://github.com/svg/svgo) first (~24k).

**Comment by cvan** [comment]
I know it's not best practice for self-contained libraries, but how about we just split the SVG into a separate file. Let people include them when they download their copies of `webvr-polyfill`. Or let them require it conditionally, something like: `require('webvr-polyfill.assets/rotate-instructions.svg')` (I know with Webpack the syntax would be different, but with Browserify, you could do something like that). Also, just serving them on [this project's GitHub Pages](https://googlevr.github.io/webvr-polyfill/) would be helpful for folks too.

**Comment by jsantell** [comment]
I'd love to add webpack imports to make this nicer since #241 landed, but that'd require others importing via webpack to also need the same webpack configuration, although it'd make a nicer experience for those just using the built script.

**Comment by jsantell** [comment]
With WakeLock being a dependency, and rotate instructions now [moved to its own file](https://github.com/googlevr/cardboard-vr-display/commit/73df574c9c61d73a10b81e308bc0d13e19bf44d9), this looks solved. Looking at ways to reducing this filesize as well while addressing #210
