### ISSUE TITLE
does not work in firefox?

### ISSUE THREAD

**Issue by makc** [googlevr/webvr-polyfill#126]
all polyfill=1 links look like this:
![screen shot 2016-06-08 at 16 15 15](https://cloud.githubusercontent.com/assets/242577/15897334/5f7d11ae-2d94-11e6-851d-4958d25e203d.png)

**Comment by borismus** [comment]
Does Firefox support webvr 1.0 yet?

**Comment by makc** [comment]
No idea, just thought this 'polyfill' would make it work regardless

**Comment by cvan** [comment]
@toji's examples don't work with the pre-1 version of the polyfill. The polyfill will polyfill navigator.getVRDisplays but only on mobile. You can force it to polyfill navigator.getVRDevices with an option on WebVRConfig. But this won't matter soon anyway. Firefox Nightly is getting 1.0 support. We have working builds; just need to get merged after code review rounds.

**Comment by capnmidnight** [comment]
@cvan: so a month and a half later, is there any news on Nightly getting WebVR 1.0?

**Comment by cvan** [comment]
@capnmidnight: We have Nightly builds of WebVR 1.0 support in Firefox under review. @kearwood's 1.0 support is landing in Firefox Nightly in the next week or so. @caseyyee is also tracking Firefox support, so feel free to ping any one of us about questions re: parity or status. We'll try to be more transparent and expedient going forward. Thanks for your patience.

**Comment by sohow** [comment]
@cvan how about that "1.0 support is landing in Firefox Nightly in the next week or so"

**Comment by cvan** [comment]
@sohow: you can follow its progress on https://bugzilla.mozilla.org/show_bug.cgi?id=1250244 to see that it's being actively worked on.

**Comment by cvan** [comment]
_**Firefox 1.0 support has landed in Nightly!**_

https://twitter.com/kearwoodgilbert/status/765697899359449088

**Comment by makc** [comment]
You mean they have fixed the bugs that made Firefox 51.0 incompatible with Firefox 1.0 ?

**Comment by caseyyee** [comment]
@makc what he meant was that WebVR 1.0 API support has landed into Firefox Nightly edition.   You can download at https://nightly.mozilla.org/
