### ISSUE TITLE
Problems with cardboard distorter in PlayCanvas

### ISSUE THREAD

**Issue by daredevildave** [googlevr/webvr-polyfill#130]
I'm trying to get the latest version of the Polyfill working with PlayCanvas and I'm having some issues where the cardboard renderer doesn't seem to work correctly.

I have three scenes:

Our VR starter kit: https://playcanv.as/b/7NvIiWR8/ seems to work fine.

A simple test scene of cubes renders a blank screen when applying the distorter: http://playcanvas.github.io/webvr/examples/simple-scene/

The Orange Room scene renders at 1/4 scale in the bottom right of the screen: https://playcanv.as/b/oDFMxRAs/

Any ideas why the second two of these scenes don't work?

**Comment by borismus** [comment]
Hi David, sorry for delay. Are you using the latest webvr-polyfill? What
device are you testing on? Does the sample work for you?
http://borismus.github.io/webvr-polyfill/examples/basic

**Comment by daredevildave** [comment]
Hi Boris,

Reproduced on Nexus 5X and Galaxy S6. It's using the version from commit 85f657cd502ec9417bf26b87c3cb2afa6a70e079.

Thanks
