### ISSUE TITLE
Eye viewport overlap

### ISSUE THREAD

**Issue by AdaRoseCannon** [googlevr/webvr-polyfill#133]
Thanks for the awesome polyfill!!

Platform Samsung Galaxy S6, Chrome 50 and Samsung Browser

![screenshot_20160701-131420](https://cloud.githubusercontent.com/assets/4225330/16521253/94250cbc-3f8d-11e6-984f-b9ea01acb880.png)

Works correctly on v0.9.15 breaks on v1.0.0. (Samsung browser)
Reproducible in Chrome 50 as well. (Thanks for getting it working in Chrome in v1.0.0 :D)

**Comment by borismus** [comment]
Could you link to a reduced test case?

**Comment by jsantell** [comment]
Are you finding any matches in the local dpdb? There are a few Samsung Galaxy models in there. If not, [adding new device parameters](https://github.com/WebVRRocks/webvr-polyfill-dpdb/blob/master/README.md) I'm hoping will work, but we may need to do more than just matching UA strings ([more info in this issue for the Galaxy S6](https://github.com/googlevr/webvr-polyfill/issues/129))

**Comment by jsantell** [comment]
Moving Samsung resolution handling to fix incorrect distortions to https://github.com/googlevr/cardboard-vr-display/issues/7
