### ISSUE TITLE
Disable head tracking when orientation sensor returns 0,0,0,0

### ISSUE THREAD

**Issue by bnolan** [googlevr/webvr-polyfill#134]
On my shield TV / androids without a gyroscope, the orientation must return 0,0,0,0, because the viewport is looking down at the ground. It'd be great to detect this and disable head tracking, point the camera forward and go back to swipe to look around.

**Comment by brianchirls** [comment]
This is a good idea in principle; it would also be useful when debugging on desktop browser dev tools emulating a mobile device. But @bnolan how would this work within the WebVR API?

**Comment by borismus** [comment]
Scope of polyfill is to provide the behavior of the WebVR API. This has a
few implications:

1. In cases where there is no valid gyroscope, the polyfill should probably
be disabled altogether.

2. Touch panning and mouse/keyboard controls doesn't belong in the
polyfill, but will probably eventually migrate to the webvr-boilerplate.

**Comment by AVGP** [comment]
Hm, sounds like `VRDisplay.capabilities.hasOrientation` should return `false` in that case...
But that'd mean you have a VR device without position and orientation... what would be a reasonable behaviour? Disable the polyfill maybe?

**Comment by jsantell** [comment]
This request has been open for awhile, and as discussed, unclear the best way to handle this. Closing this for now, please reopen if I'm misunderstanding or if there's a solution we're missing. Thanks!
