### ISSUE TITLE
Separate rendering for each eye

### ISSUE THREAD

**Issue by pindiespace** [googlevr/webvr-polyfill#143]
Does the polyfill have the ability to render to separate renderers? I have a request from a client who is interested in this function (ditto for video embedded in the scene).

**Comment by borismus** [comment]
Not separate renderers, but you can render separate scenes. Curious: what's the use case for multiple renderers?

**Comment by pindiespace** [comment]
The idea was that video performance in a VR scene (actually lightboxing the video across the scene on user choice) would work better this way. You would render incoming video in one renderer, scene in another. Don't know if this is practical, or if it would help. 

Maybe having multiple offscreen renderers could provide a boost via the Offscreen Canvas API, since you could have multiple renderers off the main JS thread.

This in turn might help the poor embedded video performance in webvr recently discussed on the slack channel.
