### ISSUE TITLE
Enable antialias

### ISSUE THREAD

**Issue by HalfdanJ** [googlevr/webvr-polyfill#144]
Im trying to test stereoscopic rendering with antialiasing enabled (In THREE.js). In the VREffect code i've change one line of code so predistored is set to true (to disable distortion effects in polyfill), but I'm still not able to get antialias to work. Any pointers to what else i should do? Antialias works when its not in presentation mode. 

```
resolve( vrDisplay.requestPresent( [ { source: canvas, predistorted: true } ] ) );
```

**Comment by borismus** [comment]
Hey! Not sure about what's causing this. I think an important thing is that we support antialiasing in the native WebVR API @toji

**Comment by toji** [comment]
This is a limitation of the polyfill and always will be for WebGL 1. The only surface that can be antialiased is the backbuffer, but the polyfill works by intercepting the draw calls and redirecting them to an intermediate surface. This means that we lose antialiasing on a technicality.

That won't be an issue for the native implementation.

**Comment by marcio-ao** [comment]
Would it be possible to do FXAA on the intermediate buffer?
