### ISSUE TITLE
Touch Screen movement on Keyboard and Mouse Devices

### ISSUE THREAD

**Issue by sjfricke** [googlevr/webvr-polyfill#146]
I ran into this issue due to trying my application on an Asus Transformer laptop. The device will register as a `Mouse and Keyboard VRDisplay (webvr-polyfill)` because it should, but if I don't have the keyboard (detach it) then I am not able to move around in the scene as the "touch" event listeners are not in the `mouse-keyboard-vr-display.js` file

I cannot see the harm in having touch enabled as if the device doesn't have touch it won't trigger anyway. If anything an option to enable that for an application would be nice as I had to adjust it on my application

**Comment by borismus** [comment]
Thanks for flagging. I agree that we should have support for both if both are available.

FYI both mouse look and touch panning support will be moved from out of the polyfill and into the boilerplate in the near future.

**Comment by jsantell** [comment]
MouseKeyboardVRDisplay has been removed in [0.10.0](https://github.com/googlevr/webvr-polyfill/releases/tag/v0.10.0)
