### ISSUE TITLE
eye viewport widths larger than screen on iphone 5 and ipod 6

### ISSUE THREAD

**Issue by tommytee** [googlevr/webvr-polyfill#147]
Each eye viewport seems clipped. ( or zoomed in? )
( screenshots from iphone 5 )

![img_0003](https://cloud.githubusercontent.com/assets/4148420/18262308/2d17b7fc-73b5-11e6-9dfb-c1e3fd7c1649.jpg)
![img_0008](https://cloud.githubusercontent.com/assets/4148420/18262266/c9b7cd64-73b4-11e6-871d-14b684d0953f.jpg)
![img_0010](https://cloud.githubusercontent.com/assets/4148420/18262271/d1759ffe-73b4-11e6-8611-af875f62068e.jpg)
![img_0007](https://cloud.githubusercontent.com/assets/4148420/18262275/db4b6aae-73b4-11e6-9a01-36187d6e6d9b.jpg)
## For comparison here are similar android screenshots

![screenshot_20160905-200543](https://cloud.githubusercontent.com/assets/4148420/18262344/758678de-73b5-11e6-8d2d-192466b6f752.png)
![screenshot_20160905-200822](https://cloud.githubusercontent.com/assets/4148420/18262353/7f8462f6-73b5-11e6-90f5-ff3be81d4d84.png)
![screenshot_20160905-200704](https://cloud.githubusercontent.com/assets/4148420/18262363/a9de50ac-73b5-11e6-9cb4-44cc68b54b42.png)

I'm having the same problem on an ipod 6.  (both report a screen resolution of 640 x 1136)  I have not tested other ios devices.

I can quick-fix issue by changing the dpi in the dpdb. 
   "dpi": [ 317.1, 320.2 ] changed to [ 225, 227.2 ] 

but this seems wrong.

**Comment by borismus** [comment]
Yes definitely an issue... Unfortunately don't have an iPhone 5 to test on.

**Comment by cvan** [comment]
Could be different, but perhaps this issue is related to #140?

**Comment by borismus** [comment]
Good point, might actually not be wrong. Does it look wrong on device?

@Brian, unfortunately given my team's focus on Daydream, just haven't had
time to split things up or add to dpdb.

**Comment by tommytee** [comment]
It is definitely wrong.  I have an iphone 5 and am willing to spend some time on this if someone could point in the right direction.

**Comment by tommytee** [comment]
I have a new ipod touch and cardboard viewer.   its the same, seems less than ideal, but may be correct.
