### ISSUE TITLE
Javascript error on all WebVR.info/samples on desktop

### ISSUE THREAD

**Issue by odysseyjason** [googlevr/webvr-polyfill#150]
When using Chrome 52 or Firefox 46 with the webvr.info/samples on a machine without a VR device attached, the following errors are produced in console:

Chrome:
webvr-polyfill.js:5421 Uncaught (in promise) TypeError: Cannot read property 'fieldOfView' of null(…)

Firefox:
TypeError: parameters is null webvr-polyfill.js:5421:5

(Windows 10, on desktop and laptop)  Samples work fine on Chrome and Firefox Mobile browsers

**Comment by borismus** [comment]
Yep, I'm seeing it too. /cc @toji

**Comment by toji** [comment]
Fixed in latest update to #149
