### ISSUE TITLE
Should not fire vrpresentdisplaychange if already presenting

### ISSUE THREAD

**Issue by brianchirls** [googlevr/webvr-polyfill#154]
The spec has been changed to clarify that the event should not fire when changing the `VRLayer` parameters. It should only display when entering or exiting presentation.

> **onvrdisplaypresentchange** A user agent MUST dispatch this event type to indicate that a VRDisplay has begun or ended VR presentation. This event should not fire on subsequent calls to requestPresent() after the VRDisplay has already begun VR presentation.

This isn't absolutely critical, as I believe it doesn't hurt anything to fire these extra events. But it's not strictly conformant to the spec.

I believe you can start here:
https://github.com/borismus/webvr-polyfill/blob/master/src/base.js#L189-L216

**Comment by brianchirls** [comment]
See also: https://github.com/mrdoob/three.js/pull/9778

**Comment by borismus** [comment]
Thanks Brian, a PR would be much appreciated!

**Comment by brianchirls** [comment]
Closing, because @AVGP fixed this in #166.
