### ISSUE TITLE
Transfer ownership of this repo

### ISSUE THREAD

**Issue by cvan** [googlevr/webvr-polyfill#162]
Hey, @borismus, would it be possible to give commit access to some folks? @toji, @brianchirls, and I have the [most numbers of merged commits](https://github.com/borismus/webvr-polyfill/graphs/contributors) to this repo.

It would be nice to have the repo live in a WebVR community org. I've been contacted GitHub Support twice to try to get ownership of https://github.com/webvr, and they've forwarded messages of mine to the owner, but the person has never responded (and evidently has been active, but hasn't created any repos under https://github.com/webvr). Instead, I've created https://github.com/web-vr. If you'd like, we could transfer the repo there.

If not, that's fine. If you're comfortable with it, @borismus, would it be possible to grant at least commit access to @toji, @brianchirls, and myself so we could merge pull requests?

**Comment by borismus** [comment]
Hey Chris, short term plan was to move this repository to googlevr and add Brandon as a committer. I'd be comfortable adding others once we have a way to unit test. My main concern at this point are platform specific regressions. The iOS implementation is especially important, and feels especially fragile...

**Comment by brianchirls** [comment]
@borismus Sounds like a good plan, and I agree completely about iOS.

Anybody here have much experience with writing those kinds of tests? I mean, how do you automatically test device orientation on an iphone?

**Comment by cvan** [comment]
That all sounds good. Definitely agree re: the fragility of the Fullscreen vs. mock-Fullscreen logic. Thanks for the update.

**Comment by borismus** [comment]
Ownership transferred. I don't know how to automate those kinds of very OS-specific tests.

**Comment by cvan** [comment]
> I don't know how to automate those kinds of very OS-specific tests.

[Browserstack](https://www.browserstack.com/) and [Webdriver](http://webdriver.io) are the best. I've been just doing automation with PhantomJS/chrome-remote-runtime (Chromium) and SlimerJS (Firefox) though lately.

**Comment by borismus** [comment]
Do those test on real devices? The issues to catch so far have been very
specific to iOS.

**Comment by brianchirls** [comment]
@borismus: Agreed. And they're often things that require real devices or at least an iOS simulator for bugs in implementation and physical orientation. It's definitely not enough to, for example, run in Chrome Dev Tools emulator mode to check screen dimensions.

**Comment by cvan** [comment]
Yes, browserstack tests on real devices with video captures.
