### ISSUE TITLE
Add parameter to disable so many console.logs..

### ISSUE THREAD

**Issue by cnspaha** [googlevr/webvr-polyfill#163]
Probably we should add an parameter so we can disable the console.logs..
I don't see any good reason, why the console.logs still fires when we don't have to debug and build release.

**Comment by borismus** [comment]
Fair enough. Maybe a debug get param that is false by default?

**Comment by cnspaha** [comment]
yep, would be a good idea

**Comment by borismus** [comment]
Cleaned up a lot of console.logs in https://github.com/googlevr/webvr-polyfill/commit/6f6ad2443fa9e98e6f1bf4f2a32b8638c3899a10.
