### ISSUE TITLE
Galaxy S7 | iPhone 7 | DPDB : In general how to compute?

### ISSUE THREAD

**Issue by devasur** [googlevr/webvr-polyfill#164]
Can someone please explain how to compute DBDB JSON entry for a new device.  
Taking values from http://btco-code.appspot.com/debug/screen_test.html as a starting point?

**Comment by PixelPartner** [comment]
Maybe @btco could help out, as also the new Google Pixel models are missing.
The iPhone7 and Plus model should be detected like the iPhone6/6S [Plus] models, but also those have weird stereo effects.
Meanwhile I'll try to fix it locally.

**Comment by PixelPartner** [comment]
You may try those entries in dpdb-cache.js and not load the JSON from google.

```
  { /* Galaxy S7 */
    "type": "android",
    "rules": [
      { "mdmh": "samsung/*/SM-G930F/*" },
      { "ua": "SM-G930F" }
    ],
    "dpi": 576.6,
    "bw": 3,
    "ac": 1000
  },

  { /* Galaxy S7 edge plus*/
    "type": "android",
    "rules": [
      { "mdmh": "samsung/*/SM-G935F/*" },
      { "ua": "SM-G935F" }
    ],
    "dpi": 534,
    "bw": 3,
    "ac": 1000
  },


```

**Comment by jsantell** [comment]
In #233, the local DPDB has been updated and sync'd with the online version at webvr.rocks (once https://github.com/WebVRRocks/webvr-polyfill-dpdb/pull/7 is merged), including the SM-G930F and SM-G935F phones. Try the latest version which should fix this -- please reopen if this does not fix the issue. 

Also for finding DPDB values, check out this link https://github.com/WebVRRocks/webvr-polyfill-dpdb/pull/9 which should help.

Thanks!

**Comment by cvan** [comment]
Now at https://github.com/WebVRRocks/webvr-polyfill-dpdb#adding-a-device - thanks, @jsantell!
