### ISSUE TITLE
iOS requestPresent doesn't hide other DOM elements

### ISSUE THREAD

**Issue by HalfdanJ** [googlevr/webvr-polyfill#172]
When going to fullscreen mode on android calling requestPresent, all other DOM elements on the screen disappear since the canvas is fullscreen. But on iOS where we can't fullscreen, other DOM elements aren't hidden. 

Is this the intention? it doesn't seem very practical since it results in different experiences on Android and iOS.

**Comment by borismus** [comment]
Like you said we don't have full screen in iOS so the results are different
anyway.

You can hide the DOM elements if you'd like. Just subscribe to the vr event
that fires when you change modes.

**Comment by jsantell** [comment]
What Boris said, I think it's out of scope to polyfill a fullscreen implementation for iOS in this case, but responding to `window.addEventListener('vrdisplaypresentchange', () => hideUI())` should work in this case
