### ISSUE TITLE
Support I-Frames through PostMessage

### ISSUE THREAD

**Issue by ngokevin** [googlevr/webvr-polyfill#173]
Safari has a rule that disallows an I-Frame to access `deviceorientation` events to get rotation data. On [aframe.io](https://aframe.io), we've had to limit the example scenes we show on mobile to scenes hosted on the same domain.

We can work around this by using postMessage. The parent window has a small script that continuously emits a postMessage with device orientation data. Then we have webvr-polyfill listen to the postMessage and send that data through the polyfill to support the I-Frame use case.

**Comment by borismus** [comment]
Are you suggesting to add a listener for these synthetic deviceorientation
events? If so I think that's reasonable. Open to PRs.

**Comment by htmlr** [comment]
@ngokevin can you share the code snippet that does this device orientation update via postMessage ?
I was considering using iframes as a way to load scenes asynchronously via the frame into a page

**Comment by ngokevin** [comment]
I don't have code snippets, but the pseudocode is:

`window.top` script:

```js
window.addEventListener('devicemotion', function (evt) {
  iframes.forEach(function (iframe) {
    iframe.contentWindow.postMessage({name: 'devicemotionpolyfillupdate', acceleration: evt.acceleration, ...});
  });
});
```

Polyfill / I-Frame content script:

```js
window.addEventListener('message', function (evt) {
  if (evt.data.name !== 'devicemotionpolyfillupdate') { return; }
  // Tell polyfill to update camera using device motion data.
});
```

**Comment by jsantell** [comment]
Added an example usage of iframes in the [cardboard-vr-display README](https://github.com/googlevr/cardboard-vr-display#i-frames), as well fixed the issue with working with [cross-origin iframes](https://github.com/googlevr/webvr-polyfill/issues/271)
