### ISSUE TITLE
Problems in VR mode

### ISSUE THREAD

**Issue by Ariel-zhangyue** [googlevr/webvr-polyfill#178]
When I use Aframe, it seems the stereoscopic does not match up.. Although the two scene for each eyes are different.
![proj](https://cloud.githubusercontent.com/assets/22290786/20468598/1477bb02-afd3-11e6-9fd4-d53720791bf8.png)
And below is the console message:
<img width="827" alt="console message" src="https://cloud.githubusercontent.com/assets/22290786/20468605/2586a2d2-afd3-11e6-8466-03035090a5ec.png">
The problems seems the same as [https://github.com/googlevr/webvr-polyfill/issues/176](url)

Should I change some parameters to make  that works fine?  
Thanks in advance!

**Comment by jsantell** [comment]
It sounds like your device couldn't be exactly matched in the dpdb, so falls back to general device properties that may be close. Check out the info here on how to find your device's info and how to add it to the dpdb which should give the correct distortion for your device: https://github.com/WebVRRocks/webvr-polyfill-dpdb/pull/9

Please reopen if you still see this issue with the correct device properties. Thanks!
