### ISSUE TITLE
DPDB_CACHE has duplicate entries for ios devices (aka iPhones)

### ISSUE THREAD

**Issue by PixelPartner** [googlevr/webvr-polyfill#181]
Why are all "ios" related entries mentioned twice ?

I was investigating this because whenever I use an iPhone6/7 the stereo settings are weird (see screencapture below).

![a-frame_bug](https://cloud.githubusercontent.com/assets/73567/20930130/abd52732-bbcc-11e6-8a75-f0f16e774b05.PNG)

Same cardboards v1/v2 work fine with most Android phones.

**Comment by HalfdanJ** [comment]
Seems to be fixed by #183?

**Comment by jsantell** [comment]
In #233, the local DPDB has been updated and sync'd with the online version at webvr.rocks (once https://github.com/WebVRRocks/webvr-polyfill-dpdb/pull/7 is merged). Try the latest version which should fix this -- please reopen if this does not fix the issue. Thanks!
