### ISSUE TITLE
Adding DayDream to Viewers

### ISSUE THREAD

**Issue by cnspaha** [googlevr/webvr-polyfill#182]
We currently only have CardboardV1 and CardboardV2 as Viewers.
Would it be possible to add DayDream also to them? I would do it myself, but can't figure out where to get all the data (inverseCoefficients, distortionCoefficients, ...) for it.

**Comment by borismus** [comment]
Daydream uses the same params as V2.

**Comment by cnspaha** [comment]
ah okay, good to know. So if I choose V2 in the polyfill it should be fine when using daydream?

**Comment by borismus** [comment]
Yes. If the phone is properly detected. Dpdb is slightly stale.

**Comment by jsantell** [comment]
This issue appears to be solved, please reopen if that is not the case -- thanks!
