### ISSUE TITLE
inverseCoefficients are undocumented

### ISSUE THREAD

**Issue by hfiguiere** [googlevr/webvr-polyfill#186]
Issue #60 say to use profile generator. While the output can be interpreted to be added to the polyfill in the device info section, there is no indication how to compute `inverseCoefficients`, even though device-info.js say they could be calculated:

https://github.com/googlevr/webvr-polyfill/blob/349394834fc3613c76ba8314a3a6ac121ea5c99c/src/device-info.js#L359

**Comment by jsantell** [comment]
As the inverse coefficients aren't even used currently, it's unlikely more work would be done here

**Comment by jsantell** [comment]
See #145 if you're still curious on the math behind this
