### ISSUE TITLE
Missing Smartphone

### ISSUE THREAD

**Issue by mn-martin** [googlevr/webvr-polyfill#188]
Please add the Sony Xperia Z2 (D6503) to dpdb-cache.js

**Comment by thoragio** [comment]
Download the [Device Info app](https://play.google.com/store/apps/details?id=com.jphilli85.deviceinfo) to your phone.
Then take screenshots of the General Information and Display sections (see [this post](https://github.com/googlevr/webvr-polyfill/issues/176#issuecomment-262112686) for an example) and post them here.

**Comment by jsantell** [comment]
Please see https://github.com/WebVRRocks/webvr-polyfill-dpdb/pull/9 for finding your device's info and adding it to the dpdb. Thanks!
