### ISSUE TITLE
How to calculate new device to DPDB?

### ISSUE THREAD

**Issue by movprojects** [googlevr/webvr-polyfill#191]
can someone point me in the right direction on what values must be entered for a new device in the DPDB cache file? here is the output of its metrics

UA: Mozilla/5.0 (Linux; Android 5.1.1; EMBT3C Build/R1.0.0) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/39.0.0.0 Safari/537.36
computed resolution: 1280 x 720
screen.width: 1280
screen.height: 720
screen.availWidth: 1280
screen.availHeight: 720
window.devicePixelRatio: 1

what values must be entered in such an entry as:

  {
    "type": "android",
    "rules": [
      { "mdmh": "asus/*/Nexus 7/*" },
      { "ua": "Nexus 7" }
    ],
    "dpi": [ 320.8, 323.0 ],
    "bw": 3,
    "ac": 500
  }

**Comment by movprojects** [comment]
anyone?

**Comment by ichengde** [comment]
```
    // device.dpi might be an array of [ xdpi, ydpi] or just a scalar.
    var xdpi = device.dpi[0] || device.dpi;
    var ydpi = device.dpi[1] || device.dpi;

    return new DeviceParams({ xdpi: xdpi, ydpi: ydpi, bevelMm: device.bw });
```
maybe
xdpi = screen.width / Device width inch.
device.bw is bezel width, change this to the width of your devices bezel.
Display size: 5.94" × 3.71" = 22.02in² (15.08cm × 9.42cm = 142.08cm²) at 323.45 PPI, 0.0785mm dot pitch, 104620 PPI²

**Comment by jsantell** [comment]
Please see https://github.com/WebVRRocks/webvr-polyfill-dpdb/pull/9 on finding and contributing your device information to the dpdb. Thanks!
