### ISSUE TITLE
Daydream controller simulation

### ISSUE THREAD

**Issue by tentone** [googlevr/webvr-polyfill#193]
Hi

I was thinking about the possibility of adding a daydream controller simulation to the WebVR polyfill (or as a extension since its not something that is part of the webvr spec at all)

This could be done having the "virtual daydream remote" always pointing in the same direction the user is looking at, that could work well to most of the pointing and teleportation interactions.

I haven't figured out a good way to simulate the track-pad and button, (i dont belive they are usable for WebVR content are they?)

If this is something that people think can be usefull i can try to implement it.

Cumps

**Comment by cvan** [comment]
Check out https://github.com/ryanbetts/dayframe
