### ISSUE TITLE
Chrome keep alive doesn't work

### ISSUE THREAD

**Issue by HalfdanJ** [googlevr/webvr-polyfill#194]
The trick to keep iOS from going to sleep doesn't work in Chrome on iOS, only in Safari.  Tested on the [basic example](http://googlevr.github.io/webvr-polyfill/examples/basic/)

**Comment by HalfdanJ** [comment]
It's now also the case on latest stable chrome on android (56), not sure when it happened.

**Comment by HalfdanJ** [comment]
Might be fixed by #206

**Comment by HalfdanJ** [comment]
@toji Would be great to get you to look at this

**Comment by toji** [comment]
Merged #206, hopefully that fixes it.
