### ISSUE TITLE
Uncaught TypeError: Cannot redefine property: vrEnabled

### ISSUE THREAD

**Issue by derhuebiii** [googlevr/webvr-polyfill#200]
**Description:**
I am creating an editor for HTML content where one building block is for aframe blocks. aframe is using WebVR polyfill as I am testing in Chrome. 
For this I am using an iframe to which the HTML code gets pushed via document.open/write/close.

If I push an aframe scene the first time, this works all fine. If I do it a second time, I get the error:

```
Uncaught TypeError: Cannot redefine property: vrEnabled
    at Function.defineProperty (<anonymous>)
    at M.enablePolyfill (webvr-polyfill.js:7699)
    at new M (webvr-polyfill.js:7631)
    at Object.M.14../util.js (webvr-polyfill.js:5606)
    at s (webvr-polyfill.js:1)
    at e (webvr-polyfill.js:1)
    at webvr-polyfill.js:1
    at u (webvr-polyfill.js:1)
    at Object.<anonymous> (webvr-polyfill.js:1)
    at Object.50 (webvr-polyfill.js:7830)
```
 
I solved my problem by adding "configurable=true" to the webvr code:

> WebVRPolyfill.prototype.enablePolyfill = function() {
>   // Provide navigator.getVRDisplays.
>   navigator.getVRDisplays = this.getVRDisplays.bind(this);
> 
>   // Provide the VRDisplay object.
>   window.VRDisplay = VRDisplay;
> 
>   // Provide navigator.vrEnabled.
>   var self = this;
>   Object.defineProperty(navigator, 'vrEnabled', {
>     configurable:true,

Is there another way to avoid this or can configurable be added to the property?

Thanks!
Kr,
Gerd

- A-Frame Version: 0.5 incl. webvr-polyfill
- Platform / Device: Chrome (or probably any browser with WebVR)
- Reproducible Code Snippet or URL:

**Comment by Disorrder** [comment]
+1

It appears when I try to `registerComponent` or `registerGeometry` or `registerPrimitive`

**Comment by josephrexme** [comment]
This problem is not fixed for me

**Comment by jsantell** [comment]
@josephrexme `vrEnabled` was never a part of the spec, so it has been removed awhile back, I think in the `0.10.0` release.

**Comment by josephrexme** [comment]
I should've updated. This was my bad. I mistakenly added the polyfill to a page twice. All good!

**Comment by jsantell** [comment]
@josephrexme glad to hear! :smile:
