### ISSUE TITLE
getFrameData() broken on some phones in latest Chrome

### ISSUE THREAD

**Issue by HalfdanJ** [googlevr/webvr-polyfill#202]
There is a bug on certain Android phones using the latest versions of Chrome that support native WebVR. The bug has at least been verified on Samsung S7 Edge. 

When WebVR is enabled in the browser, but there is no headset connected and polyfill kicks in, the `getFrameData` returns `null` in orientation. I traced the error to be happening in [frameDataFromPose#L391](https://github.com/googlevr/webvr-polyfill/blob/1047fd29bc33d62d922a13c9c29c51fb23eb7cd5/src/util.js#L391). When the VRFramePos type is defined by the browser, the setter never changes the value of the object. Interestingly this works fine on other phones supporting native webvr. My guess is this is happening because the getter on pose never reads the actual object value that is being set. 

Here is a screenshot showing its not setting the orientation, comparing `frameData.pose` with `pose`  

![image](https://cloud.githubusercontent.com/assets/227529/23859835/6617f64c-07db-11e7-8e50-74d0659a7b27.png)

**Comment by HalfdanJ** [comment]
https://github.com/googlevr/webvr-polyfill/issues/202 seems to be referring the same problem

**Comment by HalfdanJ** [comment]
https://github.com/googlevr/webvr-polyfill/issues/199 seems to be similar issue

**Comment by toji** [comment]
This is probably because the `pose` on a native `VRFrameData` object is read only. _sigh_ Might be able to do some interesting getter/setter monkey punching to fix it.

**Comment by brianchirls** [comment]
This sounds very similar to #197, which was just merged yesterday. @HalfdanJ Can you upgrade to the latest version and try again?

**Comment by HalfdanJ** [comment]
Perfect, works

**Comment by toji** [comment]
Excellent. Thank you Brian!

**Comment by brianchirls** [comment]
@toji I think by this point I owed you one ;-)
