### ISSUE TITLE
VRDisplay is not capable of presenting

### ISSUE THREAD

**Issue by makc** [googlevr/webvr-polyfill#205]
I am getting this with mouse-controlled debug device. What other use would this device have if it cant actually go into VR mode?

**Comment by SpaceHexagon** [comment]
I'm having this too.. sine the oculus driver updated, it seems :/

**Comment by jsantell** [comment]
The MouseKeyboardVRDisplay is for manipulating orientation via mouse and keyboard and the desktop display is already rendering the scene -- what are the expectations here? This VRDisplay is only available when not on mobile and we cannot load a CardboardVRDisplay.

**Comment by makc** [comment]
I was thinking this could help to develop vr on desktop, cardboard-style, but with keyboard/mouse instead of gyroscope.

**Comment by jsantell** [comment]
That how it the MouseKeyboardVRDisplay works right now, except there's nothing to "present" to -- see the [example](http://googlevr.github.io/webvr-polyfill/examples/basic/) here. Presenting only applies when there's an HMD, or in Cardboard/Mobile case, distorted lens rendering, and on desktop, there's no change. Do you mean that you want the distorted lens view on desktop when calling `requestPresent()`? If you'd want that, you can try [this chrome extension](https://chrome.google.com/webstore/detail/webvr-api-emulation/gbdnpaebafagioggnhkacnaaahpiefil), but again, I'm not sure what the expectations are for `requestPresent` while on a non-mobile, non-HMD display

**Comment by jsantell** [comment]
You can see [in the example](http://googlevr.github.io/webvr-polyfill/examples/basic/) that calling VR mode will also throw the "VRDisplay is not capable of presenting." error which is expected behaviour. If you think there's a more intuitive way of interpreting presenting on a desktop other than mono-vision, please follow up with another issue with a proposal. Thanks!
