### ISSUE TITLE
Release and publish to npm

### ISSUE THREAD

**Issue by jwerle** [googlevr/webvr-polyfill#214]
#200 is causing an error for us. Can we get a release on npm please? :]
cc @vipyne

**Comment by cvan** [comment]
@toji can you bump the version (`npm version patch && git push --tags`) and publish `0.9.27` to `npm` (`npm publish`)?

**Comment by toji** [comment]
I tried but I don't have permission for the npm repo. Paging @borismus to either push or give me permission to do so.

**Comment by borismus** [comment]
I've pushed 0.9.27 to npm. @toji you should now have the ability to push too.

**Comment by toji** [comment]
Awesome! Thanks!

**Comment by jwerle** [comment]
ty !
