### ISSUE TITLE
Create a script run by Travis CI to auto-build dist `build` files upon merges pushed to `master`

### ISSUE THREAD

**Issue by cvan** [googlevr/webvr-polyfill#216]
PR #209 adds initial support for Travis CI, with a [`.travis.yml` file](https://github.com/googlevr/webvr-polyfill/pull/209/files#diff-354f30a63fb0907d4ad57269548329e3).

Upon successful merging of Pull Requests into the upstream `master` branch, the `build` files should be automatically generated (instead of manually now).

The [`.travis.yml` file](https://github.com/googlevr/webvr-polyfill/pull/209/files#diff-354f30a63fb0907d4ad57269548329e3) in PR #209 should be adjusted to contain the following:

```yaml
branches:
  only:
  - master

script:
  - npm run build
  - npm run min

after_success:
  - ./scripts/deploy.sh
```

And the `./scripts/deploy.sh` script (see [this example](https://github.com/cvan/webvr/blob/ca0e903/scripts/deploy.sh), or the examples listed below, for inspiration) would run as a bot, on behalf of a user (with a custom GitHub Token with `push` access permissions to this repo; ping, @toji), that commits the changes with the updated dist `build/` files (after calling `npm run build && npm run dist`) and pushes to upstream `master`.

Whenever the a `push` payload request from the GitHub Webhook hits the Travis CI Webhook endpoint, Travis CI would check that a build  just run `npm run build && npm run min` on `master` branch.

<hr>

Inspiration:

* https://github.com/cvan/webvr/blob/ca0e903/scripts/deploy.sh (and https://github.com/cvan/webvr/blob/ca0e903/.travis.yml)
* https://github.com/aframevr/a-frobot

**Comment by jsantell** [comment]
This is a great idea, but unfortunately we cannot have non-Google bots that have write access to the code -- that being said, a script for maintainers to auto-build/increment package/publish would definitely be helpful in supporting faster development times -- I'll check it out.

Thanks @cvan!
