### ISSUE TITLE
Google vr how to set VR model

### ISSUE THREAD

**Issue by Lincoln-xzc** [googlevr/webvr-polyfill#218]
How to set VR model,in the google vr method is not exist

**Comment by cvan** [comment]
What do you mean by "VR model"?

**Comment by Lincoln-xzc** [comment]
Sorry,I'm wrong.Should be said to be how to set up VR mode,
In the web vr document which did not see the set method,
I tried so the configuration parameters are not OK.

**Comment by jsantell** [comment]
@Lincoln-xzc check out the [example for the polyfill](http://googlevr.github.io/webvr-polyfill/examples/basic/) on how this works with Three.js scenes. Also, [webvr.info](https://webvr.info/samples/) has some good samples, and [aframe](https://aframe.io) is great if you want to get started fast with VR scenes that "just work".

If you encounter any issues with the polyfill, please file a bug here -- thanks!
