### ISSUE TITLE
Switch to vr from full screen 

### ISSUE THREAD

**Issue by liorfrenkel** [googlevr/webvr-polyfill#219]
It is currently possible to switch to vr from full screen, but then pressing on the back arrow makes everything stuck. 
Pressing escape on the other hand works, switching back to the normal state. 

Any solution or work around? 

to see the problem:

1. go to full screen - manager.button.emit('fs');
2. then go to vr manager.button.emit('vr');
3. press the back arrow

**Comment by jsantell** [comment]
What platform and page is this? "Pressing escape" sounds like you're on desktop, but presenting via VR is not possible while on desktop. What is `manager.button`?

**Comment by liorfrenkel** [comment]
hi @jsantell , yeah sorry I was using this with google vr view., testing in chrome dev tools...
what I meant was calling `requestPresent` while already in fullscreen.
I actually solved this locally for me, changing the fullscreen element to be the document.body and not the wrapper.
 
Thanks,
Lior

**Comment by jsantell** [comment]
This looks outside of the scope of the polyfill. I'm glad you found a work around with vr view, though -- thanks for filing!
