### ISSUE TITLE
Merge conflicts in release build

### ISSUE THREAD

**Issue by bjornbytes** [googlevr/webvr-polyfill#223]
It looks like some merge conflicts snuck in to `webvr-polyfill.min.js`.

**Comment by cvan** [comment]
Thanks for filing! I opened PR #225 to fix the builds (I think a manual merge conflict caused this). See [my comment here](https://github.com/googlevr/webvr-polyfill/pull/225#issue-225898055) about automating this in the future.

**Comment by jsantell** [comment]
Closed via #233
