### ISSUE TITLE
No WebVRConfig for 3D scale (eye separation)

### ISSUE THREAD

**Issue by SpaceHexagon** [googlevr/webvr-polyfill#226]

**Comment by SpaceHexagon** [comment]
Actually an issue with three.js https://github.com/mrdoob/three.js/blob/7d847de7bd8c999b822f2bcb4f43caebfcfecff0/examples/js/effects/VREffect.js

**Comment by cvan** [comment]
@SpaceHexagon: did you file an issue in three.js for this? at the very least, one or both of the projects ought to document this (IMO).

**Comment by SpaceHexagon** [comment]
@cvan I suggested it here https://github.com/mrdoob/three.js/issues/8829 ( Last I attempted the solution of reducing the scene scale, I ended up with weird (z-buffer?) glitches )
