### ISSUE TITLE
Embed - view distortion on iOS

### ISSUE THREAD

**Issue by pioncz** [googlevr/webvr-polyfill#227]
When i open website with iframe, the view in the iframe looks dostorted. Is it caused by no support for `deviceorientation` events on ios?

I have Threejs scene, with sphere around camera. When i rotate camera on android, sphere looks goods, but on ios it looks like camera is not in the center of the scene.
Android:
![android](https://cloud.githubusercontent.com/assets/1942019/25792509/3f5c7858-33c7-11e7-8743-a4205ea3db07.png)
Iphone 5s - camera rotated:
![ios2](https://cloud.githubusercontent.com/assets/1942019/25792507/3f5a83f4-33c7-11e7-9c55-c34f7b6b5309.PNG)
Iphone 5s - camera not rotated:
![ios1](https://cloud.githubusercontent.com/assets/1942019/25792508/3f5ad3f4-33c7-11e7-9938-ad4ff3ea1bb1.PNG)

Is there anything i can do now to fix it?

**Comment by cvan** [comment]
Can you upload your test case somewhere so I can take a peek?

**Comment by pioncz** [comment]
Updating some libs helped and it wasn't polyfill fault.
Thanks

**Comment by cvan** [comment]
np, thanks for filing anyway 👍
