### ISSUE TITLE
Exception thrown when loading DPDB (cross origin error)

### ISSUE THREAD

**Issue by marciot** [googlevr/webvr-polyfill#245]
I am getting an exception thrown when webvr-polyfill tries loading the online DPDB. The browser throws a CORS exception and the polyfill fails to load. To make the code more robust, I suggest wrap a try and catch around the code, ie:

    function Dpdb(fetchOnline, onDeviceParamsUpdated) {
      // Start with the offline DPDB cache while we are loading the real one.
      this.dpdb = DPDB_CACHE;

      // Calculate device params based on the offline version of the DPDB.
      this.recalculateDeviceParams_();

      // XHR to fetch online DPDB file, if requested.
      if (fetchOnline) {
        // Set the callback.
        this.onDeviceParamsUpdated = onDeviceParamsUpdated;

        try {
          var xhr = new XMLHttpRequest();
          var obj = this;
          xhr.open('GET', ONLINE_DPDB_URL, true);
          xhr.addEventListener('load', function() {
            obj.loading = false;
            if (xhr.status >= 200 && xhr.status <= 299) {
              // Success.
              obj.dpdb = JSON.parse(xhr.response);
              obj.recalculateDeviceParams_();
            } else {
              // Error loading the DPDB.
              console.error('Error loading online DPDB!');
            }
          });
          xhr.send();
        } catch(e) {
          // Error loading the DPDB.
          console.error('Error loading online DPDB!');
        }
      }
    }

**Comment by marciot** [comment]
Hum. No longer able to reproduce this error. Maybe the problem has been corrected on the server, or maybe I was mistaken about the symptoms.

**Comment by marciot** [comment]
I am seeing this error again. I suggest implementing the fix above as the server seems to occasionally reject CORS requests for the PBDB.

**Comment by jsantell** [comment]
Where is the line that's throwing? Maybe an error handler `xhr.addEventListener('error', ...)` would work, I'm surprised the try/catch block solves this

**Comment by marciot** [comment]
I have tried reproducing this error on numerous browsers and I have been unable to reproduce it using a cross-origin request. I believe you are correct, my explanation does not seem to be correct.

What is strange is that on at least two occasions I have had my WebVR apps crash and adding the try/catch has enabled them to work again. I recall seeing the CORR warning on the browser console, but perhaps something else unrelated is triggering that.

Given that this problem seems to occur infrequently, it's very hard to troubleshoot, but I will keep an eye out for it. At the moment, all I can think of is that maybe the transfer is succeeding but the data is bad and perhaps JSON.parse is throwing an exception?

**Comment by jsantell** [comment]
It's possible we could be getting back some non-JSON parseable object which would throw, but that still wouldn't be catchable due to async XHR call. An example of try/catch wrapped around an async call that is *not* caught:

```js
function test () {
  try {
    setTimeout(function(){ throw new Error('not caught!') }, 10);
  } catch(e) { console.error('caught!!!!') }
}
```

Do you see any other errors logged while encountering it? Does it always crash whenever you do encounter the CORS warning?

**Comment by jsantell** [comment]
Closing this issue -- please reopen if you see this issue again or have more information -- thanks!
