### ISSUE TITLE
Right eye, split in half Samsung S4

### ISSUE THREAD

**Issue by marciot** [googlevr/webvr-polyfill#247]
There is an odd situation on the Samsung S4 where the right eye field is cut in half (or shifted over by half). Is there any workaround to this problem?

**Comment by marciot** [comment]
![screenshot_2017-05-31-15-37-38](https://cloud.githubusercontent.com/assets/6752228/26655582/a1a8481c-4618-11e7-8e89-e5e86815aaa2.png)

**Comment by jsantell** [comment]
That's unusual -- I wonder if we have correct device information for the Samsung S4. What is the value if you enter this in the console: `navigator.getVRDisplays().then(function (displays) { console.log(displays[0].dpdb_.deviceParams)  })`

You can learn more about using devtools on a remote device [here](https://developers.google.com/web/tools/chrome-devtools/remote-debugging/) if you're unfamiliar

**Comment by jsantell** [comment]
Also, is this reproduceable on [this example](http://googlevr.github.io/webvr-polyfill/examples/basic/)?

**Comment by marciot** [comment]
Okay. So interestingly the example works on his device, but this one does not http://devel.lulzbot.com/vr/taz.

I set up a test page to extract the dpdb and here is what I get. It appears as if dpdb is null:

![screenshot_2017-06-01-08-21-16](https://cloud.githubusercontent.com/assets/6752228/26684437/3d78c862-46a4-11e7-8807-315d707b1bb6.png)

**Comment by marciot** [comment]
I found out the correct repo to update is https://github.com/WebVRRocks/webvr-polyfill-dpdb. I'll clone that and see if I can do a push request with corrected settings.

**Comment by jsantell** [comment]
What version of the polyfill are you using? I'm getting weird results on my Nexus 6p as well; I'm guessing it's an outdated version of the polyfill (which could potentially clobber updated dpdb values) -- drop the latest build from http://googlevr.github.io/webvr-polyfill/build/webvr-polyfill.min.js and see if that has better results

**Comment by marcio-ao** [comment]
Also, in looking through the example, I see it has a button for setting full screen. Is this necessary? I had assumed, perhaps incorrectly, that startPresenting would go into full screen for me.

**Comment by marcio-ao** [comment]
@jsantell: I'll try the latest build. Thank you.

**Comment by jsantell** [comment]
Since the webvr info sample works, and the Taz page does not work for both the Samsung S4 and Nexus devices (my own as well), it sounds like something with your setting up the VR code. I'd take a look at the [webvr.info sample source](https://github.com/toji/webvr.info/blob/master/samples/03-vr-presentation.html) and make sure you're using it correctly.

I'll merge in the Samsung S4 DPDB values in the next release, although the latest version of the polyfill should pull it in from the URL at runtime getting those values since the webvr-polyfill-dpdb has been updated and serves from Github. Hope this helps!

**Comment by marciot** [comment]
It would be trivial to modify the code so that it is setup exactly as in the WebVR Example source, so I'll do that tomorrow and see if it helps. But just as an rational for why I am doing it differently, the WebVR demo is resizing the canvas based on window.innerWidth/window.innerHeight. This pattern tends to be used a lot in WebGL code, but it does not allow the canvas to be positioned anywhere other than covering the entire window. Over time I have adopted a different pattern that relies on canvas.clientWidth/canvas.clientHeight instead. This gives the designer the flexibility to place the WebGL canvas anywhere on the page -- the designer can still choose to use CSS to make it cover the window, but by choice, not necessity.

While 99% of the WebVR use cases may indeed be full screen, I could imagine a blog post that would wrap text around a WebGL canvas, but yet allow the user to click a button to view that same scene in VR. It would be nice is that were possible.

Anyhow, the demo I am doing for LulzBots is full screen, so like I said it's no big deal to make work exactly like the WebVR Example, but if that does turn out to be the problem, would you be willing to look into why using clientWidth/clientHeight is causing issues? I could make a simple test case from the WebVR Example to demonstrate the issue.

-- Marcio

-- Marcio

**Comment by jsantell** [comment]
The fullscreen issue is probably related/similar to #138 -- if you had a simple test case for this it'd be even easier to fix and would be appreciated!

**Comment by marciot** [comment]
That's easy :) I cloned this repo and modified the WebGL Example to use clientWidth and clientHeight, as I am doing in the TAZ demo:

http://www.marciot.com/webvr-polyfill/examples/basic

The source is here:

https://github.com/marciot/webvr-polyfill/tree/master/examples/basic

I don't have access to a Nexus, so if you don't mind running it on yours I would really appreciate it. If it fails, then it will be a simple test case of the issue I am encountering.

My variation works fine on my iPhone 6 as well as an Android Fire tablet I use for testing, which is why I had believed it to be correct until now.  Having converted your example, I saw that it has "renderer.setPixelRatio", which my version does not (if I put it in, the image gets distorted on my test devices). If I were to take a wild guess, I bet maybe it has something to do which why my variant works on my devices but not others. I feel the answer is right under my nose, but I don't know what it is.

-- Marcio

**Comment by marciot** [comment]
I added another example. This shows the reason I think using canvas.clientWidth and canvas.clientHeight is preferable to window.innerWidth and window.innerHeight. It shows the hypothetical case in which the user may not want the canvas to be fullscreen in regular viewing mode. It mostly works on my iPhone, except that the page margin gets applied when going in VR mode.

http://www.marciot.com/webvr-polyfill/examples/wraparound

**Comment by jsantell** [comment]
Thanks for the steps to reproduce @marciot! I'll check this out more next week

**Comment by marcio-ao** [comment]
A small update on this. Switching the code over to work exactly like WebVR Example, using window.innerWidth/window.innerHeight has been confirmed to have solved the problem.

I'm still holding out hope on getting the version with canvas.clientWidth/canvas.clientHeight to work though. Will let you know as I learn more.

**Comment by marcio-ao** [comment]
It looks like my canvas.clientWidth/canvas.clientHeight demo works too. I think the fix was adding "renderer.setPixelRatio", which was missing in my code.
