### ISSUE TITLE
Make configuration non-global and WebVRPolyfill a standalone constructor for Webpack/Browserify

### ISSUE THREAD

**Issue by brianchirls** [googlevr/webvr-polyfill#256]
There are or have been a number of cases where code references a value on `WebVRConfig` and assumes that value exists. But those values may be left undefined, especially as new properties are added.

This just hit me with `WebVRConfig.GET_VR_DISPLAYS_TIMEOUT`. I didn't notice that the property was added, especially since it happened in a patch-level upgrade.

We should always be checking that values exist for these properties and using a default if they don't.

**Comment by jsantell** [comment]
The user defined values get [merged into the defaults](https://github.com/googlevr/webvr-polyfill/blob/c0213841ba75a489f04bac252888dfb58f8ddb39/src/main.js#L19) and set on `window.WebVRConfig` -- `GET_VR_DISPLAYS_TIMEOUT` will be undefined on older versions where it does not exist, but where/how are you recreating this scenario? Are you just importing `src/webvr-polyfill` in some browserify/webpack environment?

This polyfill was built off the idea of just including the script and it just working, but that works less well for importing it in a browserify environment -- I think a solution here is parsing any `window.WebVRConfig` values and allowing the WebVRPolyfill object to accept a configuration if pulling it in the browserify environment (which I'm assuming is where this is happening)

**Comment by brianchirls** [comment]
Yeah, I'm importing `src/webvr-polyfill` in webpack. I'm not sure it's strictly necessary for my particular case anymore - I think it's left over from an older version. But for the sake of discipline and future-proofiness, it's probably best to set the defaults in the `WebVRPolyfill` constructor or at the point where each setting is needed. If you're going to have an object/constructor/class in its own file, it should function as such, if possible.

**Comment by jsantell** [comment]
This project wasn't really designed with module importing via webpack in mind, but something I'd like to fix in the future, reducing dependency on global configuration and making it easy to work within webpack, but still supporting the <script> tag workflow as well. I'll update the title to indicate the problem and fix. Thanks!

**Comment by jsantell** [comment]
The [0.10.0](https://github.com/googlevr/webvr-polyfill/releases/tag/v0.10.0) changes removed the magic globals and lazy instantiation resulting in a simplified constructor -- I believe this issue is resolved, please reopen if I'm missing anything!
