### ISSUE TITLE
VRControls only work for Yaw and Roll (if no gyro is available?)

### ISSUE THREAD

**Issue by mgreter** [googlevr/webvr-polyfill#262]
Hi webvr folks.

I own a ZTE Blade 6 which unfortunately lacks a gyro (as a lot of other mid-range phones). I don't know if this is the main cluprit to my issue, but from looking over the code there is IMO a good chance. I uploaded a very initial preview that should show the issue (may work ok on your device, also glad to hear from those).

http://ocbnet.ch/gaia-vr-pre-alpha-01/three-app-build/demo/stars.html?controls=vr&stars=1

Basically I lack experience in this regard to make a good guess what the real issue is (and don't own enough test devices). But I only get visual movements top or down, but not left or right. The camera/controls are at the coordinate origin, which I guess could contribute to that issue. It works kinda ok if I use [`DeviceOrientationControls`][4] from Three.js directly, but that one seems to lack damping and/or fusion and has a pretty "jerky" behavior, but I get at least some movement in left/right direction. This could probably be improved by adding damping to the "DeviceOrientation", but not sure it will be enough ...

In comparison the android app "Sky Map" has an option to disable the gyroscope: [Not all devices have a gyro - if yours does then you'll get better results with it enabled and this box unchecked. On the other hand if your device does not have a gyro then Sky Map will probably not work if you uncheck this box.][1]

So I'm seeking for some conclusions and advice here. FWIW I've done some previous work with ie. lsm9ds1 chips to [read out][2] raw data via I2C. But I lack the knowledge and experience to make something usefull out if the raw data yet (sensor fusions). I'm probably willing to invest some time to get this working, as it should be possible from viewing other samples on this particular phone. But really wanted to first hear your opinions!? 

- Should webvr-polyfill (controls) work with phones that lack a real gyro?
- I do see the same behavior also for the [basic example in this repo][3]!
- Is this a known shortcoming, and are there any plans to address this?
- FWIW: My device only reports `NaN` for `poseSensor.gyroscope`!

As previousely pointed out, the "Sky Map" App is indeed able to track the position quite ok, once I explicitly disable the gyro in its settings. I read that it may use the internal "compass", which I'm a bit confused about what exact reading that would be (magnetometer in relation to accelerometer?). There doesn't seem to be any explicit "compass" API, beside the "deviceOrientation" one. Would be great if somebody has some pointers how to achieve best results with the available sensors on my phone. Otherwise the only starting point for me is the source code of the mentioned "Sky App" Map.

I tried to make sense out of it on my own, but have hit a wall here with my phone. Main problem I have is that I haven't yet found a JS API beside "deviceOrientation" that would give me any indication of looking around left or right. Am I missing something here and how do other Apps do this without a gyro (which I know my phone is physically lacking)? Any hints are very welcome ❗️ 

Hope you don't mind me opening this issue and all the Best!

[1]: https://github.com/sky-map-team/stardroid/blob/master/app/src/main/res/values/strings.xml#L477
[2]: https://gist.github.com/mgreter/a64bd6366fda57f08ae8
[3]: https://googlevr.github.io/webvr-polyfill/examples/basic/
[4]: http://ocbnet.ch/gaia-vr-pre-alpha-01/three-app-build/demo/stars.html?controls=dev&stars=1

**Comment by jsantell** [comment]
Thanks for filing this and giving a thorough report! Unfortunately, the [devicemotion](https://caniuse.com/#feat=deviceorientation) gyroscope information is required for this to work. I don't know of any polyfills, or if it's possible (some [information here on others looking](https://github.com/h5bp/lazyweb-requests/issues/177)). If there's a reasonable way to polyfill this, I'd love to learn more!
