### ISSUE TITLE
Log warnings on deprecated methods and properties

### ISSUE THREAD

**Issue by brianchirls** [googlevr/webvr-polyfill#265]
The following APIs have been deprecated from the 1.1 API and removed from Chrome as of v59:

- `VRDisplay.getPose()`
- `VRDisplay.resetPose()`
- `VRDisplay.isConnected`
- `VRDisplayCapabilities.hasOrientation`
- `VREyeParameters.fieldOfView`

We should at least run `console.log` with a deprecation message when any of these are accessed/called. I would also be open to throwing an error or just removing them completely. A hard failure might even be preferable because it would force someone testing on a polyfillable device to notice a failure the same way it would happen in stable Chrome.

The changes would need to happen in base.js, the cardboard display and the mouse/keyboard display.

**Comment by jsantell** [comment]
:+1: on all of these
