### ISSUE TITLE
Touch and orientation video in mobile

### ISSUE THREAD

**Issue by CesarBalzer** [googlevr/webvr-polyfill#269]
I'm trying to use this library in a mobile android/cordova project, but when I enter the video, if I turn the phone up, down, left or right works perfectly, but when I try to slide my finger on the screen to rotate the video, only works left and right.
Another difficulty that the video starts "on its back", ie instead of showing the first scene from the front, it turns 180 degrees and turns its back.
As I'm new to webvr, I'd like to know how I could solve these problems?

**Comment by CesarBalzer** [comment]
I still can not get the video of a 180 degree turn, is there any way I can force it?
Thank you

**Comment by jsantell** [comment]
@CesarBalzer sounds like this might be an issue with [vrview](https://github.com/googlevr/vrview) and not the polyfill if I understand correctly. Please file an issue there, and if I'm wrong please reopen this issue -- thanks!
