### ISSUE TITLE
IPD increased on larger QHD screens

### ISSUE THREAD

**Issue by lincolnfrog** [googlevr/webvr-polyfill#272]
This is a bug originally on vrview, which relates to missing IPD settings - "Potentially due to missing data in dpdb.json in webvr-polyfill project".
https://github.com/googlevr/vrview/issues/66

**Comment by jsantell** [comment]
Moving Samsung resolution handling to fix incorrect distortions to https://github.com/googlevr/cardboard-vr-display/issues/7
