### ISSUE TITLE
Provide custom URL to DPDB

### ISSUE THREAD

**Issue by danrossi** [googlevr/webvr-polyfill#274]
There is an enforcement to load a remote json. However it is out of date to the github version and missing Samsung S8 (webvr fully functional with flags enabled).

Needs an option to use updated cache or custom url ?

**Comment by cvan** [comment]
Can you check https://github.com/WebVRRocks/webvr-polyfill-dpdb/issues/23#issuecomment-313925532

and, yes, we can support a custom URL to use instead

**Comment by danrossi** [comment]
That is for S8+ not S8. different codes. S8+ has a bigger screen. i had to add it to a custom device json. according to the code the url is a constant.

**Comment by cvan** [comment]
this has since been updated. we should still keep this issue open to allow providing a different URL to the JSON file for a custom DPDB.

**Comment by danrossi** [comment]
It's ok thanks for that. I had to fork and modify myself to get S8 working.

**Comment by jsantell** [comment]
Updating issue title -- please update with a new issue if you're still seeing issues with S8 after updating. Thanks!

**Comment by jsantell** [comment]
Added in [cardboard-vr-display 1.0.1](https://github.com/googlevr/cardboard-vr-display), and webvr-polyfill 0.10.0, there's now a `DPDB_URL` config option
