### ISSUE TITLE
Polyfill fails on current Chrome and Safari on macOS High Sierra

### ISSUE THREAD

**Issue by joshmarinacci** [googlevr/webvr-polyfill#280]
I get an error about not being able to modify the navigator.vrEnabled property.  The root cause is that the code assumes if !navigator.vrEnabled then it should add the property. This doesn't consider if the property *is* defined and was explicitly set to false.

**Comment by cvan** [comment]
is #281 the only fix needed? can you test and report back? thanks for filing this issue and your patience 👍

**Comment by joshmarinacci** [comment]
Yep.

**Comment by jsantell** [comment]
Thanks for filing! Looks like #281 fixes this. Will cut a release later today with these changes.
