### ISSUE TITLE
ios looks blurry and low quality

### ISSUE THREAD

**Issue by tommytee** [googlevr/webvr-polyfill#289]
ios devices look bad in vr mode.  Everything is blurry compared to Android. 

Why is that?

**Comment by jsantell** [comment]
You could try different values of `BUFFER_SCALE` and see if that helps. Also depending on your iOS version, [aframe uses a work around](https://github.com/aframevr/aframe/blob/af155ea42f856bc1bd774b0b5b609930f4eff61b/src/index.js#L39-L41) that you could be running into

**Comment by tommytee** [comment]
Changing BUFFER_SCALE to 1 fixes the issue. 
very nice.
thank you jsantell
