### ISSUE TITLE
Device Motion events not reaching Iframe (even Chrome 62 Android 7)

### ISSUE THREAD

**Issue by devasur** [googlevr/webvr-polyfill#293]
http://googlevr.github.io/webvr-polyfill/examples/basic/

works perfectly.  When the same page is embedded in an IFRAME device motion events not reaching WebVR.

https://devasur.github.io/webvriframe/

How to fix?  Earlier there was a special handling for synthetic event handling specific to iOS and Safari.  But now it seems the problem is there with chrome also.

**Comment by brianchirls** [comment]
It seems that iOS blocks those events on all iframes, but other browsers block events on cross-origin iframes, which I imagine will be most cases.

See also #173 and #271.

**Comment by jsantell** [comment]
Wonder if it's related to Chrome 62 in a WebView here #291

**Comment by jsantell** [comment]
This looks like a duplicate of #271 -- the patch that fixes #271 also fixes the ability for Chrome to receive cross-origin synthetic devicemotion events.
