### ISSUE TITLE
Should the polyfill be enabled if getVRDisplays is defined but no VR displays are present?

### ISSUE THREAD

**Issue by droeh** [googlevr/webvr-polyfill#299]
I'm looking into an issue[0] in Firefox for Android and narrowed it down to the fact that we have WebVR support enabled (only in nightly builds) but do not provide any VR displays. Since the decision whether or not to enable the polyfill depends only on whether or not getVRDisplays is defined, we end up in a situation where the polyfill is not enabled but WebVR is also essentially non-functional -- is this an intentional design decision or an oversight? And if it's intentional, what is the reasoning?

[0] https://bugzilla.mozilla.org/show_bug.cgi?id=1412336

**Comment by jsantell** [comment]
You may be interested in the flag `ALWAYS_APPEND_POLYFILL_DISPLAY`, which in the event that the API exists, yet no native VRDisplays available, the polyfill will kick in and provide a CardboardVRDisplay. This option lets users control whether or not they want to support the less-performant Cardboard fallback when a platform supports WebVR natively, although provides no displays.

Please reopen if I'm misunderstanding the issue!
