### ISSUE TITLE
Head-neck model for positional data

### ISSUE THREAD

**Issue by mkeblx** [googlevr/webvr-polyfill#3]
Prior to gaining positional support with the DK2 the DK1 and now the Gear VR generate approximate positional data from HMD rotation and a head-neck model that perhaps subtly but still significantly makes for a better experience. What are your thoughts on implementing somethings similar as part of GyroPositionSensorVRDevice?

**Comment by borismus** [comment]
Seems like a great idea.

**Comment by borismus** [comment]
Not sure how to achieve this. As soon as we include positional data, we look like a 6DOF headset.

**Comment by jsantell** [comment]
Open for 2+ years, no plans to support this right now
