### ISSUE TITLE
Emit `vrdisplayconnected` and `vrdisplaydisconnected` events

### ISSUE THREAD

**Issue by cvan** [googlevr/webvr-polyfill#40]
The [events](https://mozvr.github.io/webvr-spec/#interface-window) fired on `window`:
- `vrdisplayconnected` (not implemented in latest Chromium builds)
- `vrdisplaydisconnected` (not implemented)
- `vrdisplaypresentchange` (implemented)

**Comment by borismus** [comment]
Happy to accept patches for this!

**Comment by cvan** [comment]
Brandon already added support for `vrdisplaypresentchange`. We just need the other two events now.

**Comment by sandromartis** [comment]
+1 This would be amazing!

**Comment by borismus** [comment]
When is the polyfill "connected"? This doesn't make sense to me.

**Comment by gmarinov** [comment]
if the polyfill polyfills, then it's connected as soon as it populates its devices, assuming before it there's no vrdevice, otherwise what would be there to polyfill?
