### ISSUE TITLE
Starting on landscape iOS shows Cardboard modal

### ISSUE THREAD

**Issue by cvan** [googlevr/webvr-polyfill#76]
1. Holding your iPhone in landscape mode, load https://borismus.github.io/webvr-polyfill/examples/basic/
2. Click the "VR" button
3. Notice the Cardboard modal appears, even though I'm already in landscape mode :-1: 
4. Rotate the phone to portrait
5. The Cardboard modal disappears :+1:

**Comment by borismus** [comment]
When entering VR in landscape mode, the modal should still show up for a short period.
