### ISSUE TITLE
allow control over this.rotateStart for cardboard and mouse-keyboard displays

### ISSUE THREAD

**Issue by gmarinov** [googlevr/webvr-polyfill#90]
since these bind on window and do not perform any checking whether the touch or click is meant for the canvas, any other elements the canvas coexists with end up having to block the event from bubbling up.

**Comment by borismus** [comment]
Should this be bound on the canvas instead, then?

**Comment by gmarinov** [comment]
That solves the problem partially, from the POV of where the event listener should be installed. Sometimes even when the mousedown/touchdown reaches the canvas, it's desirable to disallow such "manual" panning to be initiated. Which is what `canInitiateRotation` in the PR does. Also if something sits on top of the canvas, then that may prevent the event from reaching the canvas in a situation where this is desired (which is solvable via css).

**Comment by jsantell** [comment]
With the removal of MouseKeyboardVRDisplay in [0.10.0](https://github.com/googlevr/webvr-polyfill/releases/tag/v0.10.0), I don't think this is relevant any longer -- please reopen if I'm misunderstanding, thanks!
