### ISSUE TITLE
a way for the rotate instructions interstitial to announce its show/hide-ing

### ISSUE THREAD

**Issue by gmarinov** [googlevr/webvr-polyfill#93]
e.g. `document.body.dispatchEvent(new CustomEvent('VRInstructionsShown'))`

**Comment by borismus** [comment]
Why? How are the rotate instructions not desirable?

**Comment by gmarinov** [comment]
it's desirable to sync to the interstitial becoming frontmost or hiding...

**Comment by kschzt** [comment]
@borismus it's not about desirability, this is just an event to know when it's shown / hidden

**Comment by borismus** [comment]
This can be done, propose an event name, and we can emit it. This is already done for other events like `onvrdisplaypresentchange`

**Comment by gmarinov** [comment]
well, it's up there at the very top of the post. if it needs to be in all lowercase, then that would make it "vrinstructionsshown", and its counterpart - "vrinstructionshidden".

**Comment by borismus** [comment]
How about having the vrdisplaychange event fire after the instructions are
hidden?

**Comment by gmarinov** [comment]
how would that address the 'shown' part?

**Comment by borismus** [comment]
It would not.

**Comment by gmarinov** [comment]
so can we get a `vrinstructionsshown` and `vrinstructionshidden` then?

**Comment by borismus** [comment]
Sure, please submit a PR.

**Comment by borismus** [comment]
Out of scope. Polyfill needs to track WebVR spec.
